In [207]:
import pandas as pd
taxonomy = pd.read_csv("../data/Pollen23e - original.csv")
taxonomy.head()

,class,order,family,genus,species,flora do brasil
0,Magnoliopsida,Fabales,Fabaceae,anadenanthera,anadenanthera colubrina,ok
1,Magnoliophyta,Liliopsida,Arecales,arecaceae,arecaceae,ok
2,Magnoliopsida,Lamiales,Bignoniaceae,Arrabidaea,arrabidaea florida,not_ok
3,Magnoliopsida,Rosales,Urticaceae,Cecropia,cecropia pachystachya,ok
4,Magnoliopsida,Asterales,Asteraceae,Chromolaena,chromolaena laevigata,ok

In [208]:
df= taxonomy.applymap(lambda s:s.lower() if type(s) == str else s)
classes = pd.concat([pd.get_dummies(df['order']), pd.get_dummies(df['family']),pd.get_dummies(df['genus']),pd.get_dummies(df['species'])],axis =1)

In [209]:
name = taxonomy['species'].str.replace(' ', '_')

In [210]:
df_name = pd.concat([name,classes],1)

In [12]:
mypath = '../data/pollen23e_split/test_burry'

In [76]:
for fol in folder:
    
    arquivos = (listdir(mypath+"/"+fol))
    
    for arq in arquivos:
        
        novo_nome = fol + "-" +arq.split('_')[1]
        nome_caminho = mypath+"/"+fol+"/"+novo_nome
        nome_antigo = mypath+"/"+fol+"/"+arq
        
        shutil.move(nome_antigo, nome_caminho)

In [92]:
from os import rmdir
for caminho in suffix:
    meu_caminho = (mypath_1+caminho)

    onlyfolder = [f for f in listdir(meu_caminho) if (isdir(join(meu_caminho, f)))]
    for remover in onlyfolder:
        rmdir(meu_caminho+remover)

In [195]:
arquivos = pd.DataFrame([],columns=['caminho','split','species'])
for caminho in suffix:
    meu_caminho = (mypath_1+caminho)

    arquivo = pd.DataFrame(listdir(meu_caminho),columns=['species'])
    arquivo['caminho'] = arquivo['species']
    arquivo['split'] = caminho
    
    arquivos = arquivos.append(arquivo, sort=True)

In [196]:
arquivos['species'] = arquivos['species'].str.split('-',expand=True)[0]

In [197]:
arquivos = arquivos.reset_index(drop=True)

In [212]:
rotulo = arquivos.merge(df_name, on='species')
rotulo.to_csv("rotulo.csv",index=None)

In [206]:
ls

a                  Projeto-processamento.ipynb             rotulos.csv
checkpoints/       Projeto-processamento-MultiLabel.ipynb
Convert_dir.ipynb  rotulo.csv

In [213]:
rotulo

,caminho,species,split,arecales,asterales,fabales,gentianales,lamiales,liliopsida,malpighiales,...,mimosa distans,myrcia sp,poaceae,protium sp,qualea multiflora,schinus sp,senegalia plumosa,serjania sp,syagrus oleracea,tridax procumbens
0,anadenanthera_colubrina-01.jpg,anadenanthera_colubrina,train/,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,anadenanthera_colubrina-06.jpg,anadenanthera_colubrina,train/,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,anadenanthera_colubrina-07.jpg,anadenanthera_colubrina,train/,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,anadenanthera_colubrina-09.jpg,anadenanthera_colubrina,train/,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,anadenanthera_colubrina-10.jpg,anadenanthera_colubrina,train/,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,tridax_procumbens-08.jpg,tridax_procumbens,test/,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
797,tridax_procumbens-16.jpg,tridax_procumbens,test/,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
798,tridax_procumbens-18.jpg,tridax_procumbens,test/,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
799,tridax_procumbens-24.jpg,tridax_procumbens,test/,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
800,tridax_procumbens-35.jpg,tridax_procumbens,test/,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [187]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
           rotation_range=45,
           width_shift_range=0.1,
           height_shift_range=0.1,
           shear_range=0.01,
           zoom_range=[0.9,1.25],
           horizontal_flip=True,
           vertical_flip=True,
           fill_mode='reflect',
           data_format='channels_last',
           brightness_range=[0.5, 1.5])

test_datagen = ImageDataGenerator()

In [190]:
batch_size = 64
seed = 42
train_generator = train_datagen.flow_from_dataframe(
                        dataframe = train,
                        directory =   '../data/pollen23e_split_multi/train',
                        x_col="caminho",
                        y_col=columns,
                        target_size = (299,299),
                        batch_size = batch_size,
                        save_to_dir = '../data/pollen23e_aug_multi/train',
                        save_prefix='aug', 
                        save_format='png',
                        class_mode = "other",
                        follow_links = True,
                        seed = seed)

validation_generator = train_datagen.flow_from_dataframe(
                        dataframe = val,
                        directory =   '../data/pollen23e_split_multi/val',
                        x_col="caminho",
                        y_col=columns,
                        class_mode = "other",
                        save_to_dir = '../data/pollen23e_aug_multi/val',
                        save_prefix='aug', 
                        save_format='png',
                        follow_links = True,
                        seed = seed)

test_generator = test_datagen.flow_from_dataframe(
                        dataframe = test,
                        directory =   '../data/pollen23e_split_multi/test',
                        x_col="caminho",
                        y_col=columns,
                        save_to_dir = '../data/pollen23e_aug_multi/test',
                        target_size = (299,299),
                        batch_size = batch_size,
                        class_mode = 'other',
                        follow_links = True,
                        seed = seed)

Found 480 validated image filenames.
Found 160 validated image filenames.
Found 161 validated image filenames.

### Borrando as imagens

In [23]:
for fol in folder:
    
    arquivos = (listdir(mypath+"/"+fol))
    
    for arq in arquivos:
        caminho = mypath+'/'+fol+'/'+arq
        !convert {caminho} -filter Gaussian -blur 0x8 {caminho}